name: Create each PlatformIO EleksTubeHAX environment build on multiple OSes.

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: write # Required to list/delete caches during pruning

env:
  GH_TOKEN: ${{ github.token }}
  GITHUB_TOKEN: ${{ github.token }}
  CI: true
  GH_PROMPT_DISABLED: "1"
  GH_PAGER: cat
  GH_NO_UPDATE_NOTIFIER: "1"
  PLATFORMIO_USE_SYSTEM_PYTHON: "1"
  ESPTOOL_VERSION: "5.1.0"

jobs:
  discover-envs:
    name: Discover PlatformIO environments.
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ steps.find.outputs.envs }}
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v4

      - name: Find [env:*] sections in platformio.ini file.
        id: find
        shell: bash
        run: |
          envs_json="$(
            awk '
              /^\[env:[^]]+\]/ {
                match($0, /^\[env:([^]]+)\]/, m)
                if (m[1] != "") envs[count++] = m[1]
              }
              END {
                printf("[")
                for (i=0; i<count; i++) printf("%s\"%s\"", (i>0?",":""), envs[i])
                printf("]")
              }
            ' platformio.ini
          )"
          echo "envs=${envs_json}" >> "$GITHUB_OUTPUT"
          echo "  🐞 Detected PIO environments: ${envs_json}."

  build:
    name: Build ${{ matrix.env }} on ${{ matrix.os }}.
    runs-on: ${{ matrix.os }}

    needs: discover-envs

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following 2 configurations:
      # 1. <Windows, Release, toolchain on the default runner image, default generator>
      # 2. <Linux, Release, toolchain on the default runner image, default generator>

      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:        
        # os: [ubuntu-latest] # For local testing: act can’t run runs-on: windows-latest (or macos-latest)
        os: [ubuntu-latest, windows-latest]
        env: ${{ fromJson(needs.discover-envs.outputs.envs) }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo.
        uses: actions/checkout@v4

      - name: Setup Python.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Bootstrap PlatformIO virtualenv.
        run: |
          python - <<'PY'
          import pathlib
          import subprocess
          import sys

          home = pathlib.Path.home()
          penv = home / ".platformio" / "penv"
          if sys.platform == "win32":
              python_path = penv / "Scripts" / "python.exe"
          else:
              python_path = penv / "bin" / "python"

          if not python_path.exists():
              subprocess.check_call([sys.executable, "-m", "venv", str(penv)])

          subprocess.check_call([str(python_path), "-m", "pip", "install", "--upgrade", "pip"])
          PY

      - name: Install PlatformIO + IntelHex and esptool libraries.
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade platformio intelhex "esptool==${ESPTOOL_VERSION}"
          if [[ "${RUNNER_OS}" == "Windows" ]]; then
            PENV_PY="$USERPROFILE\\.platformio\\penv\\Scripts\\python.exe"
          else
            PENV_PY="$HOME/.platformio/penv/bin/python"
          fi
          if [[ -f "$PENV_PY" ]]; then
            "$PENV_PY" -m pip install --upgrade pip
            "$PENV_PY" -m pip install --upgrade "esptool==${ESPTOOL_VERSION}"
          fi

      - name: Preinstall PlatformIO esptool tool package.
        run: |
          platformio pkg install --tool tool-esptoolpy

      - name: Hydrate tool-esptoolpy with pip distribution.
        run: |
          set -euo pipefail
          python - <<'PY'
          import os
          import shutil
          from pathlib import Path
          import esptool

          pkg_dir = Path.home() / ".platformio" / "packages" / "tool-esptoolpy"
          pkg_dir.mkdir(parents=True, exist_ok=True)

          src_dir = Path(esptool.__file__).resolve().parent
          dst_dir = pkg_dir / "esptool"
          if dst_dir.exists():
            shutil.rmtree(dst_dir)
          shutil.copytree(src_dir, dst_dir)

          (pkg_dir / "pyproject.toml").write_text("""
          [build-system]
          requires = ["setuptools>=61"]
          build-backend = "setuptools.build_meta"
          """.strip() + "\n", encoding="utf-8")

          version = os.environ.get("ESPTOOL_VERSION", getattr(esptool, "__version__", "0.0.0"))

          setup_cfg_lines = [
              "[metadata]",
              "name = esptool",
              f"version = {version}",
              "description = PlatformIO hydrated esptool package",
              "license = GPL-2.0-or-later",
              "",
              "[options]",
              "packages = find:",
              "include_package_data = True",
              "install_requires =",
              "    bitstring!=4.2.0,>=3.1.6",
              "    cryptography>=43.0.0",
              "    pyserial>=3.3",
              "    reedsolo<1.8,>=1.5.3",
              "    PyYAML>=5.1",
              "    intelhex",
              "    rich_click",
              "    click<9",
              "python_requires = >=3.8",
              "",
              "[options.entry_points]",
              "console_scripts =",
              "    esptool = esptool.__main__:main",
              "    esptool.py = esptool.__main__:main",
              "",
          ]
          (pkg_dir / "setup.cfg").write_text("\n".join(setup_cfg_lines), encoding="utf-8")
          PY

      - name: Export esptool path for PlatformIO.
        run: |
          set -euo pipefail
          ESPTOOL_PATH=$(python - <<'PY'
          import shutil
          path = shutil.which("esptool.py") or shutil.which("esptool")
          if not path:
              raise SystemExit("esptool executable not found in PATH")
          print(path, end="")
          PY
          )
          echo "Using esptool at $ESPTOOL_PATH"
          echo "PLATFORMIO_ESPTOOLPY_PATH=$ESPTOOL_PATH" >> "$GITHUB_ENV"

      - name: Shim esptool --version on Windows.
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest
          $pythonExe = Join-Path $env:pythonLocation "python.exe"
          if (-not (Test-Path $pythonExe)) {
            $pythonExe = "python"
          }

          $esptoolPath = $env:PLATFORMIO_ESPTOOLPY_PATH
          if (-not $esptoolPath) {
            throw "PLATFORMIO_ESPTOOLPY_PATH is not set; expected to point to esptool executable."
          }

          $shimDir = Split-Path $esptoolPath -Parent
          if (-not (Test-Path $shimDir)) {
            throw "Directory for esptool ($shimDir) not found."
          }

          $renamedExe = Join-Path $shimDir "esptool-real.exe"
          if ([System.IO.Path]::GetExtension($esptoolPath).Equals('.exe', [System.StringComparison]::OrdinalIgnoreCase)) {
            if (-not (Test-Path $renamedExe)) {
              Rename-Item -Path $esptoolPath -NewName (Split-Path $renamedExe -Leaf)
            }
          }

          $shimPath = Join-Path $shimDir "esptool.cmd"
          $shimContent = @"
          @echo off
          setlocal ENABLEEXTENSIONS
          set "PYTHON_EXE=$pythonExe"
          set "REAL_ESPTOOL=%~dp0esptool-real.exe"
          if "%~1"=="--version" (
            shift
            if exist "%REAL_ESPTOOL%" (
              "%REAL_ESPTOOL%" version %*
            ) else (
              "%PYTHON_EXE%" -m esptool version %*
            )
            exit /b %ERRORLEVEL%
          )
          if exist "%REAL_ESPTOOL%" (
            "%REAL_ESPTOOL%" %*
          ) else (
            "%PYTHON_EXE%" -m esptool %*
          )
          exit /b %ERRORLEVEL%
          "@

          Set-Content -Path $shimPath -Value $shimContent -Encoding Ascii
          Add-Content -Path $env:GITHUB_PATH -Value $shimDir

          $resolvedShim = (Resolve-Path $shimPath).Path
          $env:PLATFORMIO_ESPTOOLPY_PATH = $resolvedShim
          Add-Content -Path $env:GITHUB_ENV -Value "PLATFORMIO_ESPTOOLPY_PATH=$resolvedShim"
          Write-Host "Installed esptool shim at $resolvedShim (backing binary: $renamedExe)."

      - name: Initialize PlatformIO core.
        run: platformio system info

      - name: Show pip versions
        run: |
          set -euo pipefail
          echo "System python pip:" 
          python -m pip --version
          echo "System python esptool:"
          python -m esptool version
          if [[ "${RUNNER_OS}" == "Windows" ]]; then
            PENV_PY="$USERPROFILE\\.platformio\\penv\\Scripts\\python.exe"
          else
            PENV_PY="$HOME/.platformio/penv/bin/python"
          fi
          if [[ -f "$PENV_PY" ]]; then
            echo "PlatformIO penv pip:" 
            "$PENV_PY" -m pip --version
            echo "PlatformIO penv esptool:"
            "$PENV_PY" -m esptool version
          else
            echo "PlatformIO penv python not found (RUNNER_OS=$RUNNER_OS)."
          fi

      - name: Ensure default _USER_DEFINES.h file exists.
        shell: bash
        run: |
          set -euo pipefail
          SRC="include/_USER_DEFINES - empty.h"
          DST="include/_USER_DEFINES.h"
          mkdir -p "$(dirname "$DST")"
          if [[ ! -f "$DST" ]]; then
            if [[ ! -f "$SRC" ]]; then
              echo "  ❌ Source file not found: '$SRC'."
              exit 1
            fi
            cp "$SRC" "$DST"
            echo "  🔧 Copied: '$SRC' -> '$DST'."
          else
            echo "  ⚠️ Already present: '$DST'."
          fi

      - name: Build ${{ matrix.env }} environment.
        run: pio run --environment "${{ matrix.env }}" --verbose
